version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: prestashop-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: prestashop
      MYSQL_ROOT_PASSWORD: prestashops
    ports:
      - 3306:3306
    networks:
      - prestashop

  prestashop:
    image: prestashop/prestashop:1.7
    container_name: prestashop
    environment:
      DB_SERVER: mysql
    ports:
      - 8080:80
    networks:
      - prestashop

networks:
  prestashop: